In [2]:
import numpy as np

# question1:

In [5]:
a = np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# question2:

In [13]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
a = np.asarray(l1)
b = np.asarray(l2)
print(np.concatenate((a,b),axis = None))
print(np.concatenate((a,b),axis = 0))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


# question3:

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.size

9

In [20]:
arr.ndim

2

# question4:

In [42]:
a3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a4 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])

print(a3.ndim)
print(a3.shape)
print("\n")

a1 = a3[:,np.newaxis]
print(a1)
print(a1.shape)
print(a1.ndim)
print("\n")

a2 = a4[np.newaxis,:]
print(a2)
print(a2.shape)
print(a2.ndim)
print("\n")

1
(9,)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)
2


[[9 8 7 6 5 4 3 2 1]]
(1, 9)
2




In [47]:
b = np.ones((4,6))
c = b[:,np.newaxis,:]  #for 2d matrix use this and for 1d use above
c

array([[[1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.]]])

In [11]:
x = np.array([1, 2])
print(x.shape,"\t", x.ndim)
y = np.expand_dims(x, axis=0)  #equivalent to x[np.newaxis, :] or x[np.newaxis]
print(y)
print(y.shape,"\t", y.ndim)

(2,) 	 1
[[1 2]]
(1, 2) 	 2


In [12]:
x = np.array([1, 2])
print(x.shape,"\t", x.ndim)
y = np.expand_dims(x, axis=1)  #equivalent to x[:, np.newaxis]
print(y)
print(y.shape,"\t", y.ndim)

(2,) 	 1
[[1]
 [2]]
(2, 1) 	 2


# question5:

In [19]:
a = np.arange(9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(np.vstack((a,b)))
print("\n")
print(np.hstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


# question6:

In [20]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, count = np.unique(a, return_counts=True)
print(u)
print(count)

[1 2 3 4 6]
[1 3 1 1 1]
[2 4 2 2 2]


In [22]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)
print(a[indices])

['a' 'b' 'c']
[0 1 3]
['a' 'b' 'c']


In [24]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
u, indices_of_u = np.unique(a, return_inverse=True)
print(u)
print(indices_of_u)
print(a[indices_of_u])

[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 2 4 2 6 2]
