In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3],dtype = int)    # np.array([1,2,3],np.int64)
arr

array([1, 2, 3])

In [ ]:
arr[1]

2

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*we can create a array with a list, set ,tuple and using dictionary also most prefered is list and tuple because their dtype is int or float but for others they are objects*

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.size

9

In [ ]:
arr[0,1] = 4
arr

array([[1, 4, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros((3,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
a = np.ones([3,3])
a.astype(int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.arange(1,10)
print(a)
b = a.reshape(3,3)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a = np.arange(0,15,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
np.arange(5,dtype = "complex")

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
lspace = np.linspace(1,5,12)
print(lspace)
print("\n")
a = np.linspace(1,4,4)
print(a)                     # this linspace function gives 12 elements in 3 rows and 4 columns between the range of 1 to 5
print("\n")
b = np.linspace(1,15,12)    
print(b)
print("\n")
c = np.linspace(1,5,4)
print(c)  
print("\n")
d = np.linspace(2,3,num = 5,retstep=True)
print(d)
print("\n")
e = np.linspace(2,3,5,endpoint=False)
print(e)
print("\n")     
f = np.linspace(1, 10)
print(f)                #default 50 values

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


[1. 2. 3. 4.]


[ 1.          2.27272727  3.54545455  4.81818182  6.09090909  7.36363636
  8.63636364  9.90909091 11.18181818 12.45454545 13.72727273 15.        ]


[1.         2.33333333 3.66666667 5.        ]


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


[2.  2.2 2.4 2.6 2.8]


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.6326

In [ ]:
a = np.empty((4,3))
print(a)                # this empty function gives a array of garbage values where we can use update to use them

[[ 1.          2.27272727  3.54545455]
 [ 4.81818182  6.09090909  7.36363636]
 [ 8.63636364  9.90909091 11.18181818]
 [12.45454545 13.72727273 15.        ]]


In [ ]:
a = np.array([1,2,3,4,5,6])
emp_like = np.empty_like(a)    #we can get a array from other cell and make changes to it
emp_like

array([49352832,        0,        0,        0,        0,        0])

In [ ]:
ide = np.identity(5)
print(ide.astype(int))
print("\n")
e = np.eye(5)      #eye means identity matrix,difference between eye and identity is eye has k(diagonal position) value and identity doesnt have it
print(e.astype(int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
print(np.diag((1,2,3,4)))
print("\n")
print(np.diag((1,2,3,4),k=1))
print("\n")
print(np.eye(5,k=1))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
np.arange(99).reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)
print("\n")
a.ravel()                         # ravel functions is used to convert multidimensional array to 1d array

[[0 1 2]
 [3 4 5]
 [6 7 8]]




array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)
print("\n")
print(a.T)
print("\n")
print(a.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 3 6]
 [1 4 7]
 [2 5 8]]


[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [ ]:
a = np.arange(9).reshape(3,3)           #axis = 0  means columns
a.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
a = np.arange(9).reshape(3,3)          #axis = 1 means rows 
a.sum(axis=1)

array([ 3, 12, 21])

In [ ]:
a = np.arange(9).reshape(3,3)
print(a.flat)
for item in a.flat:                 #  a.flat acts as an iterator similar to that of an range function
  print(item)

0
1
2
3
4
5
6
7
8


In [ ]:
a.ndim        # ndim tells about the dimension of the matrix

2

In [ ]:
a.nbytes      # nbytes tells about the number of bytes consumed the system for this array

72

In [ ]:
 a = np.arange(9).reshape(3,3)
 print(a)
 print("\n")          # this argmax function gives the index of the maximum element
 print(a.argmax())

[[0 1 2]
 [3 4 5]
 [6 7 8]]


8


In [ ]:
a.argmax(axis=0)

array([2, 2, 2])

In [ ]:
 a = np.arange(9).reshape(3,3)
 print(a)
 print("\n")          # this argmax function gives the index of the minimum element
 print(a.argmin())

[[0 1 2]
 [3 4 5]
 [6 7 8]]


0


In [ ]:
a.argmax(axis=1)

array([2, 2, 2])

In [ ]:
a = np.array([1,3,4,7,2])
a.argsort()

array([0, 4, 1, 2, 3])

In [ ]:
a = np.array([[1,3,4],[4,9,6],[8,2,5]]) 
print(a.argsort())     
                                         
"""   0 1 2
    0  1 3 4
    1  4 9 6                  first sort the elements and compare the index for answer
    2  8 2 5    """
print("\n")
print(a.argsort(axis = 0))
print("\n")
print(a.argsort(axis = 1))



[[0 1 2]
 [0 2 1]
 [1 2 0]]


[[0 2 0]
 [1 0 2]
 [2 1 1]]


[[0 1 2]
 [0 2 1]
 [1 2 0]]


In [ ]:
 a = np.arange(9).reshape(3,3)
 b = np.arange(9).reshape(3,3)
 print(a+b)
 print("\n")
 print(a*b)
 print("\n")
 print(a@b) # or a.dot(b)
 print("\n")
print(a/b)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


[[nan  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


In [ ]:
a = np.arange(9).reshape(3,3)
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [ ]:
a = np.arange(9).reshape(3,3)
a.sum()

36

In [ ]:
a = np.arange(9).reshape(3,3)
a.max()

8

In [ ]:
a = np.arange(9).reshape(3,3)
a.min()

0

In [ ]:
a = np.arange(9).reshape(3,3)
np.where(a>2)                              # in the output 1st array represnts rows and 2nd one is columns and the output is in the format of an tuple

(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [ ]:
a = np.arange(9).reshape(3,3)
print(np.count_nonzero(a))
print("\n")
print(np.nonzero(a))

8


(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))


In [ ]:
  a = np.arange(4).reshape(4)
  a.itemsize

8

for more details search numpy methods and attributes and select docs.scipy.org

**random functions**

In [ ]:
print(np.random.rand(3,2))    #prints random values between 0 to 1
print("\n")      
print(np.random.randn(5))     #print random values between -1 to 0 to 1
print("\n")
print(np.random.randint(10,size=(3,3)))   #prints 3,3 matrix with random values int the range of 9 or (n-1)
print("\n")
print(np.random.random_sample(5))   #print random values between [0.0 t0 1.0) 1.0 not included

[[0.61230634 0.2085001 ]
 [0.03200942 0.11635372]
 [0.5584442  0.32781911]]


[-0.54965031 -2.28015691 -0.53101312  0.06869426  0.46719245]


[[2 4 6]
 [1 2 8]
 [9 8 0]]


[0.11215319 0.02768555 0.298813   0.27330842 0.36331277]
